version: "3.8"

services:
  javalin:
    container_name: javalin_spear
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./conf:/opt/spear/conf
      - ./logs:/opt/spear/logs
      - ./data:/opt/spear/data
  nginx:
    image: nginx:latest
    container_name: nginx_spear
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - javalin
