INSERT INTO ROLES (NAME, DESCRIPTION, CREATED_AT, UPDATED_AT)
VALUES ('SPEAR_MASTER', 'Unrestricted access', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO ROLES (NAME, DESCRIPTION, CREATED_AT, UPDATED_AT)
VALUES ('SPEAR_CONFIG', 'Spear configuration access', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
